---
name: Hello world workflow for C/C++ code

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

#Fix checkov permission complain
permissions: read-all

jobs:
  hworld_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{github.workspace}}/code_c      
    steps:
      - uses: actions/checkout@v4
      - name: make hworld
        run: make
      - name: run hworld
        run: ./hworld
      - name: make clean
        run: make clean

  hworld_tdd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{github.workspace}}/code_c/tdd
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install cpputest
        run: sudo apt install -y cpputest
      - name: make test     
        run: make
      - name: run test
        run: ./runtest

  hworld_lint:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      - name: Run lint
        uses: super-linter/super-linter@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIX_MARKDOWN_PRETTIER: true
          FIX_YAML_PRETTIER: true
    
  hworld_hi:
    runs-on: ubuntu-latest
    steps:
      - name: hi world
        run: echo "Hi world"
        shell: bash
      
  hworld_goodbye:
    runs-on: ubuntu-latest
    needs: hworld_hi
    steps:
      - name: goodbye world
        run: echo "Goodbye world"
        shell: bash
