---
name: Hello world workflow for C/C++ code

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  hworld_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: make hworld
        working-directory: ${{github.workspace}}/code_c
        run: make
      - name: run hworld
        working-directory: ${{github.workspace}}/code_c    
        run: ./hworld
      - name: make clean
        working-directory: ${{github.workspace}}/code_c
        run: make clean

  hworld_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run lint
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
  hworld_hi:
    runs-on: ubuntu-latest
    steps:
      - name: hi world
        run: echo "Hi world"
        shell: bash
      
  hworld_goodbye:
    runs-on: ubuntu-latest
    needs: hworld_hi
    steps:
      - name: goodbye world
        run: echo "Goodbye world"
        shell: bash
