name: Hello world workflow for C/C++ code

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  hworld_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: hello world
      run: echo "Hello world"
      shell: bash
    - name: configure hworld
      run: ls;cd code_c
      shell: bash
    - name: make hworld
      run: cd code_c;make
    - name: run hworld
      run: ./code_c/hworld
    - name: make clean
      run: cd code_c;make clean
      
  hworld_goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Goodbye world"
        shell: bash


