name: Hello world workflow for C/C++ code

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  hworld_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - working-directory: ${{github.workspace}}/code_c
    - name: make hworld
      run: make
    - name: run hworld
      run: ./hworld
    - name: make clean
      run: make clean

  hworld_hi:
    runs-on: ubuntu-latest
    steps:
      - name: hi world
        run: echo "Hi world"
        shell: bash
      
  hworld_goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "Goodbye world"
        shell: bash


